int cCompare(int side1, int place1, int side2, int place2);
int fazis2_alul();
double sarokChkSum(int num);
double sarokPosChkSum(int num);
void fazis1();
void fazis2();
void fazis3();
void fazis4();
void fazis5();
int fazis6();
void fazis7();
int run();
